name: Build and Push Dev Multi-Arch Docker Images

on:
  push:
    branches:
      - arm
    paths-ignore:
        - '**.md'
  pull_request:
    branches:
      - arm
    paths-ignore:
        - '**.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 先进行测试构建，确保构建成功
      - name: Test Docker build (Multi-platform)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: false
          tags: |
            katelyatv:latest
            katelyatv:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version
        id: get_version
        run: |
          if [ -f VERSION.txt ]; then
            VERSION=$(cat VERSION.txt)
          else
            VERSION=$(git describe --tags --always --dirty)
          fi
          # 为开发版本添加dev前缀
          DEV_VERSION="${VERSION}-dev-$(date +%Y%m%d%H%M%S)"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "DEV_VERSION=$DEV_VERSION" >> $GITHUB_OUTPUT
          echo "VERSION_WITHOUT_V=${VERSION#v}" >> $GITHUB_OUTPUT

      # 构建并推送多架构开发版镜像
      - name: Build and push multi-arch dev image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/katelyatv:${{ steps.get_version.outputs.DEV_VERSION }}
            ghcr.io/${{ github.repository_owner }}/katelyatv:dev-latest
