on:
  push:
    branches:
      - arm
  pull_request:
    branches:
      - arm

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version
        id: get_version
        run: |
          if [ -f VERSION.txt ]; then
            VERSION=$(cat VERSION.txt)
          else
            VERSION=$(git describe --tags --always --dirty)
          fi
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "VERSION_WITHOUT_V=${VERSION#v}" >> $GITHUB_OUTPUT

      # 构建并推送多架构镜像（版本标签）
      - name: Build and push multi-arch image with version tag
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/katelyatv:${{ steps.get_version.outputs.VERSION }}

      # 构建并推送多架构镜像（latest标签）
      - name: Build and push multi-arch image with latest tag
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/katelyatv:latest

      # 可选：创建 Release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          release_name: Release v${{ steps.get_version.outputs.VERSION }}
          body: |
            ## What's Changed
            ${{ github.event.head_commit.message }}

            ## Docker Images
            - Multi-arch image: `ghcr.io/${{ github.repository_owner }}/katelyatv:latest`
            - Multi-arch version: `ghcr.io/${{ github.repository_owner }}/katelyatv:${{ steps.get_version.outputs.VERSION }}

            ## Pull Commands

            ```bash
            # Pull multi-arch image (automatically selects correct architecture)
            docker pull ghcr.io/${{ github.repository_owner }}/katelyatv:latest
            docker pull ghcr.io/${{ github.repository_owner }}/katelyatv:${{ steps.get_version.outputs.VERSION }}
            ```
          draft: false
          prerelease: false
